//! Build-time AADL attribute verification (REQ-CODEGEN-VERIFY-BUILD).
//!
//! `VerifyMode::Build` emits two artifacts into the generated workspace:
//!
//! - `aadl-contract.toml` — a model-derived snapshot of every thread's
//!   timing contract (period / deadline / WCET in picoseconds), written at
//!   codegen time from the instantiated AADL model.
//! - `build.rs` — a build script that re-reads that contract and the
//!   generated component sources (`src/<process>/<thread>.rs`, whose
//!   `pub const PERIOD_PS/DEADLINE_PS/WCET_PS` constants `rust_gen` emits)
//!   and **fails compilation** if any constant diverges from the contract.
//!
//! This catches structural drift between design and code: if a human edits
//! a generated timing constant (or regenerates code from a changed model
//! without refreshing the rest), the workspace stops compiling until the
//! code and the model snapshot agree again. The build script is dependency-
//! free — it parses only the constrained subset of TOML that this generator
//! itself emits.

use spar_hir_def::instance::{ComponentInstanceIdx, SystemInstance};

use crate::{GeneratedFile, extract_timing, sanitize_ident};

/// Generate the model-contract manifest for a set of thread instances.
///
/// Threads with no timing properties at all are omitted — there is nothing
/// to verify for them at build time.
pub fn generate_contract_manifest(
    inst: &SystemInstance,
    threads: &[ComponentInstanceIdx],
) -> GeneratedFile {
    let mut toml = String::from(
        "# AADL timing contract — generated by `spar codegen --verify build`.\n\
         # DO NOT EDIT: regenerate from the AADL model. build.rs fails the\n\
         # build if the generated sources diverge from these values.\n\n",
    );

    for &idx in threads {
        let comp = inst.component(idx);
        let parent_name = comp
            .parent
            .map(|p| sanitize_ident(inst.component(p).name.as_str()))
            .unwrap_or_else(|| "root".to_string());
        let name = sanitize_ident(comp.name.as_str());
        let (period, deadline, wcet) = extract_timing(inst, idx);
        if period.is_none() && deadline.is_none() && wcet.is_none() {
            continue;
        }
        toml.push_str(&format!("[thread.\"{parent_name}/{name}\"]\n"));
        if let Some(p) = period {
            toml.push_str(&format!("period_ps = {p}\n"));
        }
        if let Some(d) = deadline {
            toml.push_str(&format!("deadline_ps = {d}\n"));
        }
        if let Some(w) = wcet {
            toml.push_str(&format!("wcet_ps = {w}\n"));
        }
        toml.push('\n');
    }

    GeneratedFile {
        path: "aadl-contract.toml".to_string(),
        content: toml,
    }
}

/// Generate the `build.rs` that verifies generated sources against the
/// contract manifest at build time.
pub fn generate_build_verifier() -> GeneratedFile {
    // The script is plain std Rust: a small parser for the manifest subset
    // emitted above + a line scan of the generated sources for the timing
    // constants. Divergence => panic! => compilation failure.
    let script = r#"//! AADL build-time contract verification — generated by spar codegen.
//! DO NOT EDIT. Fails the build when a generated timing constant in
//! crates/<process>/src/<thread>.rs diverges from aadl-contract.toml.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=aadl-contract.toml");
    println!("cargo:rerun-if-changed=crates");

    let manifest = match fs::read_to_string("aadl-contract.toml") {
        Ok(m) => m,
        Err(_) => return, // no contract => nothing to verify
    };

    // Parse the constrained manifest subset: [thread."proc/name"] sections
    // followed by `key_ps = N` lines.
    let mut contract: BTreeMap<String, BTreeMap<String, u64>> = BTreeMap::new();
    let mut current: Option<String> = None;
    for line in manifest.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("[thread.\"") {
            if let Some(name) = rest.strip_suffix("\"]") {
                current = Some(name.to_string());
                contract.entry(name.to_string()).or_default();
            }
        } else if let (Some(thread), Some((k, v))) = (&current, line.split_once('=')) {
            if let Ok(n) = v.trim().parse::<u64>() {
                contract
                    .get_mut(thread)
                    .unwrap()
                    .insert(k.trim().to_string(), n);
            }
        }
    }

    for (thread, expected) in &contract {
        // Manifest keys are "<process>/<thread>"; the source lives under that
        // process crate at crates/<process>/src/<thread>.rs.
        let (proc_dir, th_name) = thread.split_once('/').unwrap_or(("", thread.as_str()));
        let src = Path::new("crates")
            .join(proc_dir)
            .join("src")
            .join(format!("{th_name}.rs"));
        let code = match fs::read_to_string(&src) {
            Ok(c) => c,
            Err(_) => panic!(
                "AADL contract violation: thread '{thread}' is in \
                 aadl-contract.toml but {} does not exist — \
                 regenerate with `spar codegen`",
                src.display()
            ),
        };
        for (key, want) in expected {
            let konst = key.to_uppercase(); // period_ps -> PERIOD_PS
            let needle = format!("pub const {konst}: u64 = ");
            let got = code.lines().find_map(|l| {
                l.trim()
                    .strip_prefix(&needle)
                    .and_then(|rest| rest.trim_end_matches(';').parse::<u64>().ok())
            });
            match got {
                Some(v) if v == *want => {}
                Some(v) => panic!(
                    "AADL contract violation: {thread} {konst} is {v} in code \
                     but {want} in the model contract — design and code have \
                     drifted; regenerate with `spar codegen`"
                ),
                None => panic!(
                    "AADL contract violation: {thread} declares {key} = {want} \
                     in the model contract but {} has no `{needle}…;` constant",
                    src.display()
                ),
            }
        }
    }
}
"#;

    GeneratedFile {
        path: "build.rs".to_string(),
        content: script.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use spar_hir_def::item_tree::ComponentCategory;
    use spar_hir_def::name::Name;
    use spar_hir_def::resolver::GlobalScope;

    fn build_test_instance() -> SystemInstance {
        let aadl = r#"
package BuildPkg
public
    thread Worker
    end Worker;

    thread implementation Worker.Impl
        properties
            Period => 20 ms;
            Deadline => 20 ms;
    end Worker.Impl;

    process Proc
    end Proc;

    process implementation Proc.Impl
        subcomponents
            w1: thread Worker.Impl;
    end Proc.Impl;

    system Top
    end Top;

    system implementation Top.Impl
        subcomponents
            p: process Proc.Impl;
    end Top.Impl;
end BuildPkg;
"#;
        let db = spar_hir_def::HirDefDatabase::default();
        let sf = spar_base_db::SourceFile::new(&db, "b.aadl".to_string(), aadl.to_string());
        let tree = spar_hir_def::file_item_tree(&db, sf);
        let scope = GlobalScope::from_trees(vec![tree]);
        SystemInstance::instantiate(
            &scope,
            &Name::new("BuildPkg"),
            &Name::new("Top"),
            &Name::new("Impl"),
        )
    }

    #[test]
    fn contract_manifest_carries_model_timing() {
        let inst = build_test_instance();
        let threads: Vec<_> = inst
            .all_components()
            .filter(|(_, c)| c.category == ComponentCategory::Thread)
            .map(|(i, _)| i)
            .collect();
        assert!(!threads.is_empty(), "test model should have a thread");
        let manifest = generate_contract_manifest(&inst, &threads);
        assert_eq!(manifest.path, "aadl-contract.toml");
        assert!(
            manifest.content.contains("[thread.\"p/w1\"]"),
            "manifest should name the thread instance:\n{}",
            manifest.content
        );
        // 20 ms = 20_000_000_000 ps
        assert!(
            manifest.content.contains("period_ps = 20000000000"),
            "manifest should carry the model period in ps:\n{}",
            manifest.content
        );
    }

    #[test]
    fn build_verifier_is_emitted_at_workspace_root() {
        let f = generate_build_verifier();
        assert_eq!(f.path, "build.rs");
        assert!(f.content.contains("aadl-contract.toml"));
        assert!(f.content.contains("AADL contract violation"));
    }
}
