//! Rust component skeleton generation from AADL thread instances.
//!
//! For each AADL thread component, generates a Rust source file with
//! the appropriate port struct, dispatch loop, and WASI bindings.

use spar_hir_def::instance::{ComponentInstanceIdx, SystemInstance};
use spar_hir_def::item_tree::{ComponentCategory, Direction, FeatureKind};
use spar_hir_def::name::ClassifierRef;
use spar_hir_def::resolver::{DataField, DataShape, GlobalScope, ScalarKind};

use crate::{GeneratedFile, extract_timing, format_time_ps, sanitize_ident, to_pascal_case};

/// The Rust scalar for a power-of-two `Data_Size` (bytes) + numeric
/// representation, mirroring `wit_gen::scalar_wit` so the Rust port type and the
/// WIT scalar stay in lock-step (REQ-CODEGEN-WIT-RECORDS-002, #319 item 3).
/// `None` for a size WIT/Rust cannot represent no_alloc (odd size, sub-32-bit
/// float) — the caller falls back to `Vec<u8>`.
fn rust_scalar(bytes: u64, kind: ScalarKind) -> Option<&'static str> {
    match kind {
        ScalarKind::Float => match bytes {
            4 => Some("f32"),
            8 => Some("f64"),
            _ => None,
        },
        ScalarKind::Signed => match bytes {
            1 => Some("i8"),
            2 => Some("i16"),
            4 => Some("i32"),
            8 => Some("i64"),
            _ => None,
        },
        ScalarKind::Unsigned => match bytes {
            1 => Some("u8"),
            2 => Some("u16"),
            4 => Some("u32"),
            8 => Some("u64"),
            _ => None,
        },
    }
}

/// The Rust type a resolved [`DataShape`] maps to for a port field: a scalar maps
/// to a Rust primitive, a record to a struct in the crate-local `types` module
/// (generated by [`generate_types_module`]), and anything unrepresentable to
/// `Vec<u8>`. Record structs are named `to_pascal_case(type_name)` — the same
/// key `flatten_record_rust` emits — so references resolve.
fn data_shape_to_rust_type(shape: &DataShape) -> String {
    match shape {
        DataShape::Scalar { bytes, kind } => {
            rust_scalar(*bytes, *kind).map_or_else(|| "Vec<u8>".to_string(), |s| s.to_string())
        }
        DataShape::Record { type_name, .. } => {
            format!("crate::types::{}", to_pascal_case(type_name))
        }
        DataShape::Opaque => "Vec<u8>".to_string(),
    }
}

/// Generate a Rust component skeleton for a thread instance.
///
/// `scope` resolves each port's data classifier to a concrete Rust type (scalar,
/// a `crate::types` record struct, or `Vec<u8>`) so the port struct actually
/// compiles — REQ-CODEGEN-WIT-RECORDS-002 (#319 item 3). The file is emitted
/// UNDER the process crate (`crates/{proc}/src/{thread}.rs`) so the binding
/// lib.rs can `mod`-wire it.
pub fn generate_rust_component(
    inst: &SystemInstance,
    scope: &GlobalScope,
    thread_idx: ComponentInstanceIdx,
) -> GeneratedFile {
    let comp = inst.component(thread_idx);
    let name = sanitize_ident(comp.name.as_str());
    let struct_name = to_pascal_case(comp.name.as_str());
    let pkg = &comp.package;

    let (period, deadline, wcet) = extract_timing(inst, thread_idx);

    let props = inst.properties_for(thread_idx);
    let dispatch = props
        .get("Thread_Properties", "Dispatch_Protocol")
        .or_else(|| props.get("Timing_Properties", "Dispatch_Protocol"))
        .or_else(|| props.get("Deployment_Properties", "Dispatch_Protocol"))
        .or_else(|| props.get("", "Dispatch_Protocol"))
        .unwrap_or("Periodic");

    let mut code = String::new();

    // Header comment
    code.push_str(&format!(
        "//! Generated from AADL thread: {}::{}\n",
        comp.package, comp.name
    ));
    code.push_str("//! DO NOT EDIT — regenerate with `spar codegen`.\n\n");

    // Timing constants
    if let Some(p) = period {
        code.push_str(&format!("/// Thread period: {}\n", format_time_ps(p)));
        code.push_str(&format!("pub const PERIOD_PS: u64 = {p};\n"));
    }
    if let Some(d) = deadline {
        code.push_str(&format!("/// Thread deadline: {}\n", format_time_ps(d)));
        code.push_str(&format!("pub const DEADLINE_PS: u64 = {d};\n"));
    }
    if let Some(w) = wcet {
        code.push_str(&format!(
            "/// Worst-case execution time: {}\n",
            format_time_ps(w)
        ));
        code.push_str(&format!("pub const WCET_PS: u64 = {w};\n"));
    }
    code.push('\n');

    // Port struct
    code.push_str(&format!("/// Port interface for the {name} thread.\n"));
    code.push_str("#[derive(Debug, Default)]\n");
    code.push_str(&format!("pub struct {struct_name}Ports {{\n"));

    for &fi in &comp.features {
        let feat = &inst.features[fi];
        let feat_name = sanitize_ident(feat.name.as_str());
        let rust_type = feature_to_rust_type(feat.kind, &feat.classifier, scope, pkg);

        let dir_comment = match feat.direction {
            Some(Direction::In) => "in",
            Some(Direction::Out) => "out",
            Some(Direction::InOut) => "in out",
            None => "",
        };

        code.push_str(&format!(
            "    /// {dir_comment} {kind:?} port\n",
            kind = feat.kind,
        ));
        code.push_str(&format!("    pub {feat_name}: {rust_type},\n"));
    }

    code.push_str("}\n\n");

    // Component trait. The lifecycle methods are derived from the thread's
    // `Dispatch_Protocol` (REQ-CODEGEN-WIT-RECORDS-001, #319 item 7): a Periodic
    // thread exposes only `compute`; every other protocol gets the full
    // `initialize` / `compute` / `finalize`. This matches the WIT world exports
    // and the generated `Guest` impl — all three derive from `crate::Lifecycle`.
    let methods = crate::lifecycle_for(dispatch).methods();

    code.push_str(&format!(
        "/// Dispatch trait for the {name} thread ({dispatch}).\n"
    ));
    code.push_str(&format!("pub trait {struct_name}Component {{\n"));
    for (i, method) in methods.iter().enumerate() {
        code.push_str(&format!("    /// {}\n", lifecycle_doc(method, dispatch)));
        code.push_str(&format!(
            "    fn {method}(&mut self, ports: &mut {struct_name}Ports);\n"
        ));
        if i + 1 < methods.len() {
            code.push('\n');
        }
    }
    code.push_str("}\n\n");

    // Skeleton implementation
    code.push_str("/// Default implementation skeleton.\n");
    code.push_str(&format!("pub struct {struct_name}Default;\n\n"));
    code.push_str(&format!(
        "impl {struct_name}Component for {struct_name}Default {{\n"
    ));
    for (i, method) in methods.iter().enumerate() {
        code.push_str(&format!(
            "    fn {method}(&mut self, _ports: &mut {struct_name}Ports) {{\n"
        ));
        code.push_str(&format!("        // TODO: {method} logic\n"));
        code.push_str("    }\n");
        if i + 1 < methods.len() {
            code.push('\n');
        }
    }
    code.push_str("}\n");

    // Determine process parent name; the thread module lives under that crate.
    let parent_name = comp
        .parent
        .map(|p| sanitize_ident(inst.component(p).name.as_str()))
        .unwrap_or_else(|| "unknown".to_string());

    GeneratedFile {
        path: format!("crates/{parent_name}/src/{name}.rs"),
        content: code,
    }
}

/// Doc-comment text for a lifecycle trait method.
fn lifecycle_doc(method: &str, dispatch: &str) -> String {
    match method {
        "initialize" => "Called once at initialization.".to_string(),
        "compute" => format!("Called on each dispatch ({dispatch})."),
        "finalize" => "Called on finalization.".to_string(),
        other => format!("Lifecycle entry point: {other}."),
    }
}

/// Generate the per-process WIT-binding crate root (`crates/{proc}/src/lib.rs`)
/// that wires the AADL process's WIT `world` to Rust via `wit-bindgen`
/// (REQ-CODEGEN-WIT-RECORDS-001, #319 items 4 & 7).
///
/// Emits the `wit_bindgen::generate!` for the process world, a `Component`
/// struct, and an `impl Guest` whose methods are the lifecycle entry points every
/// child thread's `Dispatch_Protocol` implies — the SAME set [`crate::wit_gen`]
/// exports into the world. Because the `Guest` trait `generate!` produces is
/// derived from that world, the Rust compiler (when the crate is built) *enforces*
/// world⟷Guest alignment: a missing or misnamed method is a compile error, not a
/// silent drift (the item-7 failure mode).
///
/// Method bodies are `todo!()` stubs. This unit proves the *interface* wiring
/// compiles and matches the model; the behavior is supplied by the per-thread
/// `{Struct}Component` implementations ([`generate_rust_component`]).
pub fn generate_process_bindings(
    inst: &SystemInstance,
    proc_idx: ComponentInstanceIdx,
) -> GeneratedFile {
    let comp = inst.component(proc_idx);
    // Crate directory matches workspace_gen's `crates/{sanitize_ident(name)}`.
    let crate_dir = sanitize_ident(comp.name.as_str());
    // World name + wit file name match wit_gen exactly (kebab-case).
    let world_name = crate::wit_gen::wit_ident(comp.name.as_str());

    let child_threads: Vec<_> = comp
        .children
        .iter()
        .filter(|&&child_idx| {
            inst.component(child_idx).category == spar_hir_def::item_tree::ComponentCategory::Thread
        })
        .collect();

    let mut code = String::new();
    code.push_str(&format!(
        "//! Generated WIT bindings for AADL process: {}::{}\n",
        comp.package, comp.name
    ));
    code.push_str("//! DO NOT EDIT — regenerate with `spar codegen`.\n\n");

    // The `wit_bindgen::generate!` + `export!` glue calls its own unsafe `*_cabi`
    // shims; on the edition-2024 generated crate that trips the
    // `unsafe_op_in_unsafe_fn` future-compat lint inside macro-expanded code the
    // user cannot edit. Allow it crate-wide so the generated crate is warning-clean.
    code.push_str("#![allow(unsafe_op_in_unsafe_fn)]\n\n");

    // The crate-local record types and the per-thread component modules, wired in.
    code.push_str("mod types;\n");
    for &&child_idx in &child_threads {
        let child_mod = sanitize_ident(inst.component(child_idx).name.as_str());
        code.push_str(&format!("mod {child_mod};\n"));
    }
    code.push('\n');

    // `generate!` loads the single world file emitted by wit_gen. The path is
    // relative to this crate root (`crates/{proc}/`) reaching the top-level
    // `wit/` directory. An unqualified world name resolves because the file
    // declares exactly one package.
    code.push_str("wit_bindgen::generate!({\n");
    code.push_str(&format!("    world: \"{world_name}-world\",\n"));
    code.push_str(&format!("    path: \"../../wit/{world_name}.wit\",\n"));
    code.push_str("});\n\n");

    code.push_str("/// Component entry point, exported to the WIT world.\n");
    code.push_str("struct Component;\n\n");
    code.push_str("impl Guest for Component {\n");
    for &&child_idx in &child_threads {
        let child = inst.component(child_idx);
        let thread_kebab = crate::wit_gen::wit_ident(child.name.as_str());
        let child_mod = sanitize_ident(child.name.as_str());
        let child_struct = to_pascal_case(child.name.as_str());
        let dispatch = crate::dispatch_protocol(inst, child_idx);
        for method in crate::lifecycle_for(&dispatch).methods() {
            // wit-bindgen mangles the kebab WIT export `{thread}-{method}` to the
            // snake Rust method `{thread}_{method}`. Deriving both names from the
            // same `wit_ident` keeps them consistent; the compiler is the final
            // arbiter (see doc comment). The body delegates to the per-thread
            // component (construct-on-call); populating ports from the imported
            // WIT functions + persistent state is the deferred data plane.
            let rust_method = format!("{thread_kebab}-{method}").replace('-', "_");
            code.push_str(&format!("    fn {rust_method}() {{\n"));
            code.push_str(&format!(
                "        use crate::{child_mod}::{child_struct}Component;\n"
            ));
            code.push_str(&format!(
                "        let mut component = crate::{child_mod}::{child_struct}Default;\n"
            ));
            code.push_str(&format!(
                "        let mut ports = crate::{child_mod}::{child_struct}Ports::default();\n"
            ));
            code.push_str(&format!("        component.{method}(&mut ports);\n"));
            code.push_str("    }\n");
        }
    }
    code.push_str("}\n\n");
    code.push_str("export!(Component);\n");

    GeneratedFile {
        path: format!("crates/{crate_dir}/src/lib.rs"),
        content: code,
    }
}

/// Convert a feature kind + optional classifier to a Rust type. The classifier
/// is resolved through `scope` to its [`DataShape`] so the port type is a real,
/// defined type — a scalar, a `crate::types` record struct, or `Vec<u8>` — rather
/// than the undefined PascalCase name the old mapping produced (#319 item 3).
fn feature_to_rust_type(
    kind: FeatureKind,
    classifier: &Option<ClassifierRef>,
    scope: &GlobalScope,
    package: &spar_hir_def::name::Name,
) -> String {
    let base_type = classifier
        .as_ref()
        .map(|c| data_shape_to_rust_type(&scope.resolve_data_shape(package, c)))
        .unwrap_or_else(|| "Vec<u8>".to_string());

    match kind {
        FeatureKind::DataPort => base_type,
        FeatureKind::EventPort => "bool".to_string(),
        FeatureKind::EventDataPort => format!("Option<{base_type}>"),
        _ => base_type,
    }
}

/// Generate the crate-local `types` module (`crates/{proc}/src/types.rs`) holding
/// the Rust record structs the per-thread port structs reference. Each struct is
/// derived from the SAME [`DataShape`] `wit_gen` emits as a WIT record, so the
/// Rust struct and the WIT record cannot drift (REQ-CODEGEN-WIT-RECORDS-002,
/// #319 item 3). Structs are emitted nested-first and de-duplicated; the module
/// is (validly) empty when the process has no record-typed ports.
pub fn generate_types_module(
    inst: &SystemInstance,
    scope: &GlobalScope,
    proc_idx: ComponentInstanceIdx,
) -> GeneratedFile {
    let comp = inst.component(proc_idx);
    let crate_dir = sanitize_ident(comp.name.as_str());

    // Collect record shapes from every child thread's classifier-typed ports.
    let mut structs: Vec<(String, Vec<(String, String)>)> = Vec::new();
    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for &child_idx in &comp.children {
        let child = inst.component(child_idx);
        if child.category != ComponentCategory::Thread {
            continue;
        }
        for &fi in &child.features {
            let feat = &inst.features[fi];
            if let Some(cref) = feat.classifier.as_ref()
                && let DataShape::Record { type_name, fields } =
                    scope.resolve_data_shape(&child.package, cref)
            {
                flatten_record_rust(&type_name, &fields, &mut structs, &mut seen);
            }
        }
    }

    let mut code = String::new();
    code.push_str(&format!(
        "//! Generated record types for AADL process: {}::{}\n",
        comp.package, comp.name
    ));
    code.push_str("//! DO NOT EDIT — regenerate with `spar codegen`.\n\n");
    if structs.is_empty() {
        code.push_str("// (no record-typed ports in this process)\n");
    }
    for (sname, fields) in &structs {
        code.push_str("#[derive(Clone, Debug, Default, PartialEq)]\n");
        code.push_str(&format!("pub struct {sname} {{\n"));
        for (fname, fty) in fields {
            code.push_str(&format!("    pub {fname}: {fty},\n"));
        }
        code.push_str("}\n\n");
    }

    GeneratedFile {
        path: format!("crates/{crate_dir}/src/types.rs"),
        content: code,
    }
}

/// Recursively collect Rust struct definitions for a record shape, nested-first
/// and de-duplicated (the Rust analog of `wit_gen::flatten_record`). A nested
/// record field becomes `crate::types::{Name}` via [`data_shape_to_rust_type`].
fn flatten_record_rust(
    type_name: &str,
    fields: &[DataField],
    out: &mut Vec<(String, Vec<(String, String)>)>,
    seen: &mut std::collections::BTreeSet<String>,
) {
    let sname = to_pascal_case(type_name);
    if !seen.insert(sname.clone()) {
        return; // already collected (shared nested type)
    }
    let mut rows = Vec::with_capacity(fields.len());
    for f in fields {
        // Recurse into nested records first so they are defined before use.
        if let DataShape::Record {
            type_name: nt,
            fields: nf,
        } = &f.shape
        {
            flatten_record_rust(nt, nf, out, seen);
        }
        rows.push((
            sanitize_ident(f.name.as_str()),
            data_shape_to_rust_type(&f.shape),
        ));
    }
    out.push((sname, rows));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(to_pascal_case("ctrl_thread"), "CtrlThread");
        assert_eq!(to_pascal_case("my-component.impl"), "MyComponentImpl");
        assert_eq!(to_pascal_case("Sensor"), "Sensor");
    }

    #[test]
    fn feature_rust_type_mapping() {
        // No classifier → scope is not consulted; an empty scope is fine.
        let scope = GlobalScope::from_trees(vec![]);
        let pkg = spar_hir_def::name::Name::new("Pkg");
        assert_eq!(
            feature_to_rust_type(FeatureKind::EventPort, &None, &scope, &pkg),
            "bool"
        );
        assert_eq!(
            feature_to_rust_type(FeatureKind::DataPort, &None, &scope, &pkg),
            "Vec<u8>"
        );
        assert_eq!(
            feature_to_rust_type(FeatureKind::EventDataPort, &None, &scope, &pkg),
            "Option<Vec<u8>>"
        );
    }

    #[test]
    fn data_shape_maps_to_rust_types() {
        assert_eq!(
            data_shape_to_rust_type(&DataShape::Scalar {
                bytes: 4,
                kind: ScalarKind::Unsigned
            }),
            "u32"
        );
        assert_eq!(
            data_shape_to_rust_type(&DataShape::Scalar {
                bytes: 4,
                kind: ScalarKind::Signed
            }),
            "i32"
        );
        assert_eq!(
            data_shape_to_rust_type(&DataShape::Scalar {
                bytes: 8,
                kind: ScalarKind::Float
            }),
            "f64"
        );
        assert_eq!(
            data_shape_to_rust_type(&DataShape::Record {
                type_name: "Packet.Impl".to_string(),
                fields: vec![]
            }),
            "crate::types::PacketImpl"
        );
        assert_eq!(data_shape_to_rust_type(&DataShape::Opaque), "Vec<u8>");
        // Non-power-of-two scalar has no no_alloc Rust primitive → Vec<u8>.
        assert_eq!(
            data_shape_to_rust_type(&DataShape::Scalar {
                bytes: 3,
                kind: ScalarKind::Unsigned
            }),
            "Vec<u8>"
        );
    }
}
