// NOTE: This file was originally generated from Lean4 proofs (proofs/Codegen.lean).
// The `div_ceil` implementation was updated to use Rust's stdlib `a.div_ceil(b)` which is
// equivalent to the Lean-generated `(a + b - 1) / b` for positive b.
// The test `ceil_div_matches_lean_definition` verifies this equivalence.

//! Verified scheduling functions — generated from Lean4 proofs.
//!
//! DO NOT EDIT. This file is generated by `lake exe codegen` from
//! proofs/Proofs/Scheduling/RTA.lean. The Lean definitions are proven
//! correct (RTA convergence, monotonicity, least fixed point).
//!
//! To regenerate: cd proofs && lake exe codegen
//!
//! Proven properties:
//!   - ceil_div is monotone in numerator
//!   - interference is monotone in interval length
//!   - total_interference is monotone in interval length
//!   - rta_step is monotone
//!   - RTA iteration terminates (converges or exceeds deadline)
//!   - Converged result is the least fixed point ≥ exec time

/// Ceiling division: ⌈a / b⌉
/// Lean: def ceilDiv (a b : Nat) (_ : b > 0) : Nat := a.div_ceil(b)
#[inline]
pub fn ceil_div(a: u64, b: u64) -> u64 {
    debug_assert!(b > 0);
    a.div_ceil(b)
}

/// Interference from one higher-priority task over interval r.
/// Lean: def interference (hp : Task) (r : Nat) : Nat :=
///         ceilDiv r hp.period hp.period_pos * hp.exec
#[inline]
pub fn interference(period: u64, exec: u64, r: u64) -> u64 {
    ceil_div(r, period).saturating_mul(exec)
}

/// Total interference from all higher-priority tasks.
/// Lean: def totalInterference : List Task → Nat → Nat
///         | [], _ => 0
///         | hp :: rest, r => interference hp r + totalInterference rest r
pub fn total_interference(higher_priority: &[(u64, u64)], r: u64) -> u64 {
    let mut total: u64 = 0;
    for &(period, exec) in higher_priority {
        total = total.saturating_add(interference(period, exec, r));
    }
    total
}

/// RTA recurrence: R_{n+1} = C_i + Σ ⌈R_n / T_j⌉ × C_j
/// Lean: def rtaStep (task : Task) (hps : List Task) (r : Nat) : Nat :=
///         task.exec + totalInterference hps r
#[inline]
pub fn rta_step(exec: u64, higher_priority: &[(u64, u64)], r: u64) -> u64 {
    exec.saturating_add(total_interference(higher_priority, r))
}

/// Result of RTA fixed-point iteration.
/// Lean: proved that iteration either converges or exceeds deadline
///       within deadline + 1 steps (bounded_mono_nat_seq).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RtaResult {
    /// Fixed point found: response time = value.
    Converged(u64),
    /// Response time exceeds deadline — task misses deadline.
    Diverged,
}

/// Compute worst-case response time via fixed-point iteration.
///
/// Lean: iterN (rtaStep task hps) n task.exec
///       converges to least fixed point (rta_finds_least_fixed_point).
///
/// Max iterations bounded by deadline + 1 (rta_terminates).
pub fn compute_response_time(
    exec: u64,
    deadline: u64,
    higher_priority: &[(u64, u64)],
) -> RtaResult {
    let mut r = exec;
    for _ in 0..=deadline {
        let new_r = rta_step(exec, higher_priority, r);
        if new_r == r {
            return RtaResult::Converged(r);
        }
        if new_r > deadline {
            return RtaResult::Diverged;
        }
        r = new_r;
    }
    RtaResult::Diverged
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ceil_div_basic() {
        assert_eq!(ceil_div(7, 3), 3);
        assert_eq!(ceil_div(6, 3), 2);
        assert_eq!(ceil_div(1, 1), 1);
        assert_eq!(ceil_div(0, 5), 0);
    }

    #[test]
    fn single_task_converges() {
        // One task, no interference: R = C
        let result = compute_response_time(5, 20, &[]);
        assert_eq!(result, RtaResult::Converged(5));
    }

    #[test]
    fn two_tasks_converges() {
        // Task: exec=3, deadline=10
        // Higher priority: period=10, exec=2
        // R0 = 3, R1 = 3 + ceil(3/10)*2 = 3+2 = 5
        // R2 = 3 + ceil(5/10)*2 = 3+2 = 5 (fixed point)
        let result = compute_response_time(3, 10, &[(10, 2)]);
        assert_eq!(result, RtaResult::Converged(5));
    }

    #[test]
    fn overloaded_diverges() {
        // Task: exec=8, deadline=10
        // Higher priority: period=10, exec=5
        // R0=8, R1=8+ceil(8/10)*5=8+5=13 > 10 → diverged
        let result = compute_response_time(8, 10, &[(10, 5)]);
        assert_eq!(result, RtaResult::Diverged);
    }

    #[test]
    fn ceil_div_matches_lean_definition() {
        // Lean codegen produces: (a + b - 1) / b
        // Rust uses: a.div_ceil(b)
        // Verify equivalence for all reasonable inputs
        for a in 0..=1000_u64 {
            for b in 1..=100_u64 {
                let lean_style = (a + b - 1) / b;
                let rust_style = a.div_ceil(b);
                assert_eq!(
                    lean_style, rust_style,
                    "ceil_div mismatch for a={}, b={}",
                    a, b
                );
            }
        }
    }

    #[test]
    fn compute_response_time_matches_lean_spec() {
        // Verify the response time computation matches the formal spec:
        // R(n+1) = C_i + sum(ceil(R(n)/T_j) * C_j) for higher-priority tasks
        // Test against known manually-computed results

        // Single task: R = C = 3
        assert_eq!(compute_response_time(3, 10, &[]), RtaResult::Converged(3));

        // Two tasks: R = C1 + ceil(R/T2)*C2, fixed point
        // Task 1: C=3, T=10, D=10; HP tasks: (T=5, C=2)
        // R(0) = 3
        // R(1) = 3 + ceil(3/5)*2 = 3 + 2 = 5
        // R(2) = 3 + ceil(5/5)*2 = 3 + 2 = 5 (converged)
        assert_eq!(
            compute_response_time(3, 10, &[(5, 2)]),
            RtaResult::Converged(5)
        );
    }
}
