//! wRPC transport modeling -- generates AADL bus types for wRPC transports.
//!
//! This module generates a predefined AADL standard library representing
//! wRPC transport bus types. The generated ItemTree is equivalent to:
//!
//! ```aadl
//! package WRPC_Transports
//! public
//!   bus NATS end NATS;
//!   bus TCP end TCP;
//!   bus QUIC end QUIC;
//!   bus UDS end UDS;
//!   virtual bus WRPCProtocol end WRPCProtocol;
//! end WRPC_Transports;
//! ```

use spar_hir_def::item_tree::*;
use spar_hir_def::name::Name;

/// The bus types generated by the wRPC standard library.
const BUS_TYPES: &[(&str, ComponentCategory)] = &[
    ("NATS", ComponentCategory::Bus),
    ("TCP", ComponentCategory::Bus),
    ("QUIC", ComponentCategory::Bus),
    ("UDS", ComponentCategory::Bus),
    ("WRPCProtocol", ComponentCategory::VirtualBus),
];

/// Generate the wRPC standard library as an AADL ItemTree.
///
/// Creates a package `WRPC_Transports` with bus types for each
/// supported wRPC transport (NATS, TCP, QUIC, UDS) and a virtual
/// bus for the wRPC protocol layer.
pub fn wrpc_standard_library() -> ItemTree {
    let mut tree = ItemTree::default();
    let mut public_items = Vec::new();

    for &(name, category) in BUS_TYPES {
        let ct_idx = tree.component_types.alloc(ComponentTypeItem {
            name: Name::new(name),
            category,
            is_public: true,
            extends: None,
            features: Vec::new(),
            flow_specs: Vec::new(),
            modes: Vec::new(),
            mode_transitions: Vec::new(),
            prototypes: Vec::new(),
            property_associations: Vec::new(),
            requires_modes: false,
        });
        public_items.push(ItemRef::ComponentType(ct_idx));
    }

    tree.packages.alloc(Package {
        name: Name::new("WRPC_Transports"),
        with_clauses: Vec::new(),
        public_items,
        private_items: Vec::new(),
        renames: Vec::new(),
    });

    tree
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_wrpc_package() {
        let tree = wrpc_standard_library();
        assert_eq!(tree.packages.len(), 1);
        let (_, pkg) = tree.packages.iter().next().unwrap();
        assert_eq!(pkg.name.as_str(), "WRPC_Transports");
        assert_eq!(pkg.public_items.len(), 5, "4 bus + 1 virtual bus");
        assert!(pkg.private_items.is_empty());
    }

    #[test]
    fn bus_types_have_correct_category() {
        let tree = wrpc_standard_library();
        let bus_count = tree
            .component_types
            .iter()
            .filter(|(_, ct)| ct.category == ComponentCategory::Bus)
            .count();
        let vbus_count = tree
            .component_types
            .iter()
            .filter(|(_, ct)| ct.category == ComponentCategory::VirtualBus)
            .count();
        assert_eq!(bus_count, 4, "NATS, TCP, QUIC, UDS");
        assert_eq!(vbus_count, 1, "WRPCProtocol");
    }

    #[test]
    fn bus_type_names_are_correct() {
        let tree = wrpc_standard_library();
        let names: Vec<&str> = tree
            .component_types
            .iter()
            .map(|(_, ct)| ct.name.as_str())
            .collect();
        assert_eq!(names, &["NATS", "TCP", "QUIC", "UDS", "WRPCProtocol"]);
    }

    #[test]
    fn all_types_are_public() {
        let tree = wrpc_standard_library();
        for (_, ct) in tree.component_types.iter() {
            assert!(ct.is_public, "{} should be public", ct.name);
        }
    }

    #[test]
    fn all_types_are_empty_shells() {
        let tree = wrpc_standard_library();
        for (_, ct) in tree.component_types.iter() {
            assert!(
                ct.features.is_empty(),
                "{} should have no features",
                ct.name
            );
            assert!(
                ct.extends.is_none(),
                "{} should not extend anything",
                ct.name
            );
            assert!(
                ct.flow_specs.is_empty(),
                "{} should have no flow specs",
                ct.name
            );
            assert!(
                ct.prototypes.is_empty(),
                "{} should have no prototypes",
                ct.name
            );
        }
    }
}
